### PR TITLE
Fixed hood auto cmd to adjust angle by distance

### LINKED ISSUE #5: Add new shooter hood command to adjust hood angle based on distance reported by LimeLight
The LimeLight can tell us the distance to the target.

Add a new command to adjust the shooter hood. This command will read the distance from the LimeLight data in Network tables, and call the new method on ShooterHoodSubsystem to set the hood angle based on target distance.

### PR DESCRIPTION
**Pull request by tonypunnacherry**
Added some code to the hood command, and some new methods to the subsystem.

**New Methods**
1. getAngle() - calculates the angle using trig function, given the distance. May work depending on if the equation works for speed.
2. getAngleByZone() - gets a fixed angle given the distance using the "zones" (suggested by Mr. Dupuis, get the angle for four defined distances)
TODO: Fix the second method to have actual values in them (we need to test those still). Also, it would be nice to have the linear interpolation between the values.

**Hood Auto Command**
1. Adjusts the angle given a degree value, which can be retrieved from the new methods in the Shooter Hood Subsystem.
2. We tested it last Saturday, and it seemed to adjust the hood to a 45 degree position pretty accurately after calibration.

### CODE REVIEW

File: src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java [hunk 1]
```diff
@@ -9,21 +9,40 @@
...
-  public HoodAutoCommand() {
+  public HoodAutoCommand(ShooterHoodSubsystem shooterSubsystem) {
+    this.shooterSubsystem = shooterSubsystem;
     // Use addRequirements() here to declare subsystem dependencies.
   }
 
   // Called when the command is initially scheduled.
   @Override
   public void initialize() {
+    System.out.println("hood auto command init");
```
Comment (skallaher) [inline src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java]: I believe that we have more robust logging than this available that we should use here.

You can reference the `AutoDriveLinear.java` file to see how it is used.

File: src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java [hunk 2]
```diff
@@ -9,21 +9,40 @@
...
+    // Angle to target
+    double angle = shooterSubsystem.getAngleByZone();
+    // Ticks to Angle
+    double newposition = shooterSubsystem.findHoodTargetTicks(angle);
+    // Current Position
+    double position = shooterSubsystem.getHoodPosition();
+    // Getting Direction
+    if (position < newposition) {
```
Comment (skallaher) [inline src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java]: Instead here, you can do:
```java
isOpening = position < newposition;
```

File: src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java [hunk 3]
```diff
@@ -9,21 +9,40 @@
...
   }
 
   // Called when the command is initially scheduled.
   @Override
   public void initialize() {
+    System.out.println("hood auto command init");
+    // Angle to target
+    double angle = shooterSubsystem.getAngleByZone();
+    // Ticks to Angle
+    double newposition = shooterSubsystem.findHoodTargetTicks(angle);
```
Comment (skallaher) [inline src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java]: Could you rename this variable to use camelCase? Here it would be `newPosition`.

File: src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java [hunk 4]
```diff
@@ -9,21 +9,40 @@
...
+    // Current Position
+    double position = shooterSubsystem.getHoodPosition();
+    // Getting Direction
+    if (position < newposition) {
+       isOpening = true;
+    } else {
+      isOpening = false;
+    }
+    // Setting Motor Speed
+    shooterSubsystem.setHoodSpeed(isOpening ? -0.25 : 0.25);
```
Comment (skallaher) [inline src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java]: How do we know that the hood has been calibrated? If it hasn't, then this operation could take you to the incorrect position.

File: src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java [hunk 5]
```diff
@@ -34,11 +53,20 @@ public void execute() {
...
 
   // Returns true when the command should end.
   @Override
   public boolean isFinished() {
-    return false;
+    // Same thing in initialize
+    double angle = shooterSubsystem.getAngleByZone();
+    double position = shooterSubsystem.getHoodPosition();
+    double newposition = shooterSubsystem.findHoodTargetTicks(angle);
+    //System.out.println("Angle: " + angle + ", Position: " + position + ", New position: " + newposition);
```
Comment (skallaher) [inline src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java]: Please remove this dead code.

File: src/main/java/com/chargerrobotics/subsystems/ShooterHoodSubsystem.java [hunk 6]
```diff
@@ -57,6 +57,43 @@ public boolean isLimitSwitchTriggered() {
     public double getHoodPosition() {
         return (double)shooterHood.getSensorCollection().getQuadraturePosition();
     }
+    
+    public double getHoodAngle()  {
```
Comment (skallaher) [inline src/main/java/com/chargerrobotics/subsystems/ShooterHoodSubsystem.java]: Could you rename this to `getDesiredHoodAngle`? Otherwise, this suggests that this method returns the current hood angle.

File: src/main/java/com/chargerrobotics/subsystems/ShooterHoodSubsystem.java [hunk 7]
```diff
@@ -57,6 +57,43 @@ public boolean isLimitSwitchTriggered() {
...
+        double theta = Math.atan(2*h/d);
+        //calculations for theta of equatio
+    
+        return Math.toDegrees(theta); 
+    }
+
+    public double getAngleByZone() {
+        LimelightSubsystem limelight = LimelightSubsystem.getInstance();
+        //double d = limelight.distance();
+        double d = 50.0; //sample distance since limelight wasn't working
```
Comment (skallaher) [inline src/main/java/com/chargerrobotics/subsystems/ShooterHoodSubsystem.java]: Since this value was only used for testing, we shouldn't leave it in the code since it could just cause lots of confusion.

**Review by skallaher — CHANGES_REQUESTED** [review]
A few notes:

- Currently, the automated build is failing due to the website of one of our dependencies being down. We can just rerun this at a later time.
- It looks like your calculations for what angle to set the hood to are based on a straight line shot. Though this will probably work in most cases, you will likely have trouble when the robot is further away from the target.

File: src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java [hunk 8]
```diff
@@ -11,38 +11,40 @@
...
+    this.shooterHoodSubsystem = shooterHoodSubsystem;
     // Use addRequirements() here to declare subsystem dependencies.
   }
 
   // Called when the command is initially scheduled.
   @Override
   public void initialize() {
-    System.out.println("hood auto command init");
+    //If not calibrated, don't do anything
+    if (!shooterHoodSubsystem.getCalibrated()) return;
```
Comment (skallaher) [inline src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java]: Could you log an error here when this happens with something like:

`Cannot automatically move hood without calibrating it first!`

Comment (tonypunnacherry) [reply src/main/java/com/chargerrobotics/commands/shooter/HoodAutoCommand.java]: Okay. We will be doing one more test next week, so I will make the changes then.

**Comment by tonypunnacherry** [comment]
Closing. Use [this one](https://github.com/KentridgeRobotics/2021Robot/pull/30) instead.

**Review by skallaher — APPROVED** [review]
Applied spotless linting on your behalf. Should be good to go.
